-- Laboratorio + borse mediche (Linea Specializzata Astro Medical)
-- Rigenerabile con: npm run emit-laboratory-bags-sql

INSERT INTO public.products (sku, name, price, image_url, brand, category, description)
VALUES
  ('gima-37918', 'PROVETTA 5 ml — cilindrica 12×86 mm — PP sterile — GIMA 37918', 298, 'https://www.gimaitaly.com/images/prodotti/medium/37918.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Provetta cilindrica 5 ml in polipropilene, 12×86 mm, sterile; per campioni e laboratorio. Compatibile con rastrelliera diam. 12–13 mm. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37919', 'PROVETTA 10 ml — cilindrica 16×100 mm — PP sterile — GIMA 37919', 185, 'https://www.gimaitaly.com/images/prodotti/medium/37919.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Provetta cilindrica 10 ml in polipropilene, 16×100 mm, sterile. Compatibile con rastrelliera diam. 16 mm. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37920', 'PROVETTA 5 ml — sterile — variante — GIMA 37920', 148, 'https://www.gimaitaly.com/images/prodotti/medium/37920.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Provetta 5 ml sterile, variante listino Gima; polipropilene per uso di laboratorio. Compatibile con rastrelliera diam. 12–13 mm. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37935', 'RASTRELLIERA PER PROVETTE — diam. 12 o 13 mm — 90 posti — GIMA 37935', 32, 'https://www.gimaitaly.com/images/prodotti/medium/37935.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Rastrelliera per provette, fori diam. 12 o 13 mm, 90 posti; per organizzazione banco laboratorio. Abbinare alle provette 5 ml GIMA 37918 e 37920. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37936', 'RASTRELLIERA PER PROVETTE — diam. 16 mm — 60 posti — GIMA 37936', 32, 'https://www.gimaitaly.com/images/prodotti/medium/37936.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Rastrelliera per provette, fori diam. 16 mm, 60 posti. Abbinare alla provetta 10 ml GIMA 37919. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37950', 'PIPETTA PASTEUR 1 ml — GIMA 37950', 215, 'https://www.gimaitaly.com/images/prodotti/medium/37950.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Pipetta Pasteur monouso 1 ml per prelievi e dosaggi in laboratorio. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-37951', 'PIPETTA PASTEUR 3 ml — GIMA 37951', 215, 'https://www.gimaitaly.com/images/prodotti/medium/37951.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Pipetta Pasteur monouso 3 ml per prelievi e dosaggi in laboratorio. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27125', 'BORSA UTILITY — nylon — blu — GIMA 27125', 53, 'https://www.gimaitaly.com/images/prodotti/medium/27125.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa utility in nylon, colore blu; formato compatto per materiali e piccoli accessori sanitari. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27127', 'BORSA UTILITY — nylon — beige — GIMA 27127', 53, 'https://www.gimaitaly.com/images/prodotti/medium/27127.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa utility in nylon, colore beige. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27128', 'BORSA PROFESSIONAL — GIMA 27128', 92, 'https://www.gimaitaly.com/images/prodotti/medium/27128.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa professional per uso sanitario e ambulatoriale; capienza e organizzazione interna secondo scheda Gima. Accessorio consigliato: portafiale GIMA 27129. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27129', 'PORTAFIALE — nylon — rosso — GIMA 27129', 19.6, 'https://www.gimaitaly.com/images/prodotti/medium/27129.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Portafiale in nylon rosso per trasporto sicuro di fiale e flaconi; accessorio ideale con borse Smart e Professional. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27132', 'BORSA FIRST AID — blu — vuota — GIMA 27132', 29.3, 'https://www.gimaitaly.com/images/prodotti/medium/27132.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa primo soccorso vuota, colore blu; da completare con contenuto secondo protocollo. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27133', 'BORSA MEDICAZIONE — cordura — blu — GIMA 27133', 20.3, 'https://www.gimaitaly.com/images/prodotti/medium/27133.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa medicazione in cordura blu per materiali di cura e medicazione domiciliare/ambulatoriale. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27134', 'BORSA MULTIUSO — blu/grigio — GIMA 27134', 74.5, 'https://www.gimaitaly.com/images/prodotti/medium/27134.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa multiuso blu/grigio per equipaggiamento sanitario versatile. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27135', 'BORSA MULTIUSO — marrone/beige — GIMA 27135', 74.6, 'https://www.gimaitaly.com/images/prodotti/medium/27135.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa multiuso marrone/beige; stessa linea della versione blu/grigio. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27139', 'BORSA PORTASTRUMENTI — cordura — nera — GIMA 27139', 31.5, 'https://www.gimaitaly.com/images/prodotti/medium/27139.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa portastrumenti in cordura nera per ferri e piccolo strumentario. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27141', 'BORSA SMART CON TROLLEY — media — blu — GIMA 27141', 129, 'https://www.gimaitaly.com/images/prodotti/medium/27141.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart media con trolley integrato, colore blu; per emergenza e trasporto kit sanitari. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27150', 'BORSA SMART — piccola — rossa — GIMA 27150', 56, 'https://www.gimaitaly.com/images/prodotti/medium/27150.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart piccola rossa; linea emergenza Gima. Abbinare al portafiale GIMA 27129. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27151', 'BORSA SMART — media — rossa — GIMA 27151', 93, 'https://www.gimaitaly.com/images/prodotti/medium/27151.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart media rossa per kit sanitari e soccorso. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27152', 'BORSA SMART — media — blu — GIMA 27152', 93, 'https://www.gimaitaly.com/images/prodotti/medium/27152.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart media blu; formato intermedio della linea Smart. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27153', 'BORSA SMART — grande — rossa — GIMA 27153', 98.5, 'https://www.gimaitaly.com/images/prodotti/medium/27153.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart grande rossa; capienza superiore per equipaggiamento esteso. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27154', 'BORSA SMART CON TROLLEY — media — rossa — GIMA 27154', 154, 'https://www.gimaitaly.com/images/prodotti/medium/27154.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart media con trolley, colore rosso; mobilità per intervento e ambulanza. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27155', 'BORSA SMART PVC — piccola — rossa — GIMA 27155', 82, 'https://www.gimaitaly.com/images/prodotti/medium/27155.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart in PVC, formato piccolo, rossa; superficie lavabile. Prezzo unitario imponibile IVA esclusa.'),
  ('gima-27157', 'BORSA SMART PVC — media — rossa — GIMA 27157', 110, 'https://www.gimaitaly.com/images/prodotti/medium/27157.jpg', 'Gima', 'Linea Specializzata Astro Medical', 'Borsa Smart in PVC, formato medio, rossa. Prezzo unitario imponibile IVA esclusa.')
ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  image_url = EXCLUDED.image_url,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  description = EXCLUDED.description;
